## Server Configuration
#server.port=8082
#
#
## Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/mycomment
#spring.datasource.username=root
#spring.datasource.password=Farzan
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
## Server Configuration
#server.port=8081
#
#
## Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/mypost
#spring.datasource.username=root
#spring.datasource.password=Farzan
#
## JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#
#
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: COMMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mycomment
    username: root
    password: Farzan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MYSQL8Dialect
Server:
  port: 8082
